baseURL = "https://mansfield.ink/"
languageCode = "en-us"
title = "Mansfield.ink"
theme = "noteworthy"

googleAnalytics = "UA-219615654-1"

[params]
    email = "sgmansf@gmail.com"
    twitter = "https://twitter.com/sgmansfield"
    instagram = "https://www.instagram.com/scott.mansfield/"
    linkedin = "https://www.linkedin.com/in/scottgmansfield/"
    github = "https://github.com/ScottMansfield/"


# Menu links along the sidebar navigation.
#[[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    # Use weights otherwise Hugo alphabetizes
#    weight = 1

#[[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    weight = 2

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3

[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 4
