baseURL = "https://mansfield.ink/"
languageCode = "en-us"
title = "Mansfield.ink"
theme = "noteworthy"

googleAnalytics = "UA-219615654-1"

relativeURLs = true

[params]
    email = "sgmansf@gmail.com"
    twitter = "https://twitter.com/sgmansfield"
    instagram = "https://www.instagram.com/scott.mansfield/"
    linkedin = "https://www.linkedin.com/in/scottgmansfield/"
    github = "https://github.com/ScottMansfield/"
